// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from resources

package com.quadirkareem.protobuf;

import java.io.Serializable;

public final class SerialEntry implements Serializable {

	private static final long serialVersionUID = -1014385574500052522L;
	
	private String key;
	private String value;

	public SerialEntry() {

	}

	public SerialEntry(String key, String value) {
		this.key = key;
		this.value = value;
	}

	// getters and setters

	// key

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	// value

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
